version: '3'
services:
 elasticsearch:
  image: dock.quicket.co.kr/elasticsearch:snp
  ulimits:
   memlock:
    soft: -1
    hard: -1
   nofile:
    soft: 65536
    hard: 65536
  cap_add:
   - 'IPC_LOCK'
  environment:
   - 'http.host=0.0.0.0'
   - 'transport.host=127.0.0.1'
  ports:
   - '9200:9200'

 kibana:
  image: dock.quicket.co.kr/kibana:snp
  ports:
   - '5601:5601'
