version: '3'
services:
 es1:
  image: dock.quicket.co.kr/elasticsearch:snp
  ulimits:
   memlock:
    soft: -1
    hard: -1
   nofile:
    soft: 65536
    hard: 65536
  cap_add:
   - 'IPC_LOCK'
  environment:
   - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
     #   - 'http.host=0.0.0.0'
     #- 'transport.host=127.0.0.1'

 es2:
  image: dock.quicket.co.kr/elasticsearch:snp
  ulimits:
   memlock:
    soft: -1
    hard: -1
   nofile:
    soft: 65536
    hard: 65536
  cap_add:
   - 'IPC_LOCK'
  environment:
   - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
   - 'discovery.zen.ping.unicast.hosts=es1'
  ports:
   - '9200:9200'
   - '9300:9300'

 kibana:
  image: dock.quicket.co.kr/kibana:snp
  environment:
   - 'elasticsearch.url=http://es1:9200'
  ports:
   - '5601:5601'
